- action:
  - service: script.turn_on
    data:
      entity_id: script.sonos_say
      variables:
        where: 'living_room'
        what: 'Ding!'
  - service: light.turn_on
    entity_id:
      - light.bedroom
      - light.lees_bedside
    data:
      brightness: 150
      rgb_color: [255, 0, 0]
  alias: Doorbell Ding
  id: '1500182412602'
  trigger:
  - entity_id: binary_sensor.doorbell
    platform: state
    to: 'off'

- action:
  - service: script.turn_on
    data:
      entity_id: script.sonos_say
      variables:
        where: 'living_room'
        what: 'Dong!'
  - service: light.turn_off
    entity_id:
      - light.bedroom
      - light.lees_bedside
  alias: Doorbell Dong
  id: '1500182412603'
  trigger:
  - entity_id: binary_sensor.doorbell
    platform: state
    to: 'on'
